### ISSUE TITLE
Error: nameserver.list: Domain not found

### ISSUE THREAD

**Issue by keydon** [kegato/letsencrypt-inwx#12]
I tried to issue a new cert with multiple domains on once.
I tried serveral times, always got this error on the same domain:
```
Output from certbot-inwx-auth:
Creating TXT record...

Hook command "/usr/lib/letsencrypt-inwx/certbot-inwx-auth" returned error code 1
Error output from certbot-inwx-auth:
=> Error: nameserver.list: Domain not found
```

After deleting some no longer used DNS entries manually it finally worked.
I see your code seems to handle up to 1000 entries, but does it really tho?
Not sure exactly but I think my threshhold was 25-30 entries for one domain.

**Comment by ciphax** [comment]
Fixed in [1.1.2](https://github.com/kegato/letsencrypt-inwx/releases/tag/1.1.2).
