### ISSUE TITLE
Error: There is no nameserver for the specified domain

### ISSUE THREAD

**Issue by keydon** [kegato/letsencrypt-inwx#13]
3 months have passed and I am trying once again to renew my cert.

```
+ certbot -n --agree-tos renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/myTLD.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator manual, Installer None
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for myTLD.com
dns-01 challenge for myTLD.com
Running manual-auth-hook command: /usr/lib/letsencrypt-inwx/certbot-inwx-auth
Output from manual-auth-hook command certbot-inwx-auth:
Creating TXT record...

manual-auth-hook command "/usr/lib/letsencrypt-inwx/certbot-inwx-auth" returned error code 1
Error output from manual-auth-hook command certbot-inwx-auth:
=> Error: There is no nameserver for the specified domain
```

When I test the nameserver.list method with postman, I am getting 5 domains back. Exactly those I am trying to renew ;O So there is no paging issue this time ;)
Any ideas?

**Comment by ciphax** [comment]
I'm sorry to hear that you are having issues. I guess you are using the docker image: Are you still using an environment file which you pass with `--env-file`? If yes can you please try if mounting a [.json config file](https://github.com/kegato/letsencrypt-inwx#configuration) solves the issue?

**Comment by keydon** [comment]
Indeed, frist I tried my old setup with the env. got the same error.
Since I also saw the deprecation warning I then configured the json file, at first without the optional domains property, then with it. But with no luck, always the same error.

Is there some debug flag I could set to print out the inwx-requests going out and responses coming back? Like there is for the letsencrypt traffic?

**Comment by ciphax** [comment]
I've just released a new version that adds some debug logging: Can you please pull the new image and use either `-e LOG=letsencrypt_inwx=debug` for debug logging or `-e LOG=letsencrypt_inwx=trace` to also print api request and responses? I hope we can solve this problem if you attach an anonymized debug log to this issue.

**Comment by keydon** [comment]
Thank you for your quick help!
I think we found the problem! For some reason it processes one of my CNAMES instead my actual domain.
Background:
i.e. my TLD is `myTLD.com`
I have a couple "special" subdomains like
`a.myTLD.com` and `b.myTLD.com` which point to some stuff, but most of my use-cases point to my home-server. I do this, lazy how I am, with a wildcard-domain `*.myTLD.com` CNAME record pointing to my dynDNS provider. Also I am renewing a certificate with a wildcard for exactly this reason.

```
Running manual-cleanup-hook command: /usr/lib/letsencrypt-inwx/certbot-inwx-cleanup
manual-cleanup-hook command "/usr/lib/letsencrypt-inwx/certbot-inwx-cleanup" returned error code 1
Error output from manual-cleanup-hook command certbot-inwx-cleanup:
[2019-04-13T22:13:13Z DEBUG letsencrypt_inwx::dns] Using myDynDNS.com for _acme-challenge.myTLD.com
[2019-04-13T22:13:13Z INFO  letsencrypt_inwx::cli] Deleting TXT record...
[2019-04-13T22:13:13Z WARN  letsencrypt_inwx::cli] Domain not configured: Trying 1 configured domains
[2019-04-13T22:13:13Z DEBUG letsencrypt_inwx::inwx] Logging into account
[2019-04-13T22:13:13Z DEBUG letsencrypt_inwx::inwx] Checking domain myTLD.com
[2019-04-13T22:13:13Z DEBUG letsencrypt_inwx::inwx] myTLD.com is not the domain root of myDynDNS.com
[2019-04-13T22:13:13Z ERROR letsencrypt_inwx::cli] There is no nameserver for the specified domain
```

So I guess it should not be using `myDynDNS.com` in any way, since I have no control over my dynamic DNS provider. Can I fix that by adding an `A` record for `_acme-challenge.myTLD.com`? Or how does it 'find' `myDynDNS.com` in the first place?

**Comment by keydon** [comment]
oh I just saw your commit 9affd1cf41d781913830304134307c4432a568a4 and #9 
So I guess I have to make `_acme-challenge.myTLD.com` CNAME point to a domain, which does not have that "* -> dynDNS" issue, I will try that.

**Comment by keydon** [comment]
Yes, that worked! Perfect, thank you :)
See ya in July ;)

**Comment by ciphax** [comment]
I'm glad that you could solve your problem. I guess it would make sense to add a config option to disable following cnames

**Comment by keydon** [comment]
Or better, dont follow Wildcard-CNAMEs at all, only explizit `_acme-challenge` CNAMEs :D
EDIT: If thats distinguishable ofc :)
