### ISSUE TITLE
Certificate creation fails because No TXT record found

### ISSUE THREAD

**Issue by klausi** [kegato/letsencrypt-inwx#2]
I think the TXT record is not published fast enough? Maybe the hook that sets the DNS record should wait until the DNS record shows up on the public internet?

Output:
```
$ /opt/letsencrypt/letsencrypt-auto certonly -n --agree-tos --email me@example.com --manual --preferred-challenges=dns --manual-auth-hook /usr/lib/letsencrypt-inwx/certbot-inwx-auth --manual-cleanup-hook /usr/lib/letsencrypt-inwx/certbot-inwx-cleanup --manual-public-ip-logging-ok --server https://acme-v02.api.letsencrypt.org/directory -d *.test.example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for test.example.com
Output from certbot-inwx-auth:
Record has been created successfully.

Waiting for verification...
Cleaning up challenges
Output from certbot-inwx-cleanup:
Record has been deleted successfully.

Failed authorization procedure. test.example.com (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: No TXT record found at _acme-challenge.test.example.com

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: test.example.com
   Type:   unauthorized
   Detail: No TXT record found at _acme-challenge.test.example.com

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

**Comment by ciphax** [comment]
Is it possible that you tried to issue a certificate for the same domain just a few seconds before? I had the same issue when the validation failed on the first try because of a wrong parameter. When I tried it again I received an similar error. I guess the reason is that the previous DNS response got cached. But after waiting a few seconds and trying it again it worked.

As far as I have tested the validation always succedes as long as you do not run it multiple times in a row with a very short time between.

**Comment by klausi** [comment]
I issued a certificate for the same domain, but it was ~1 hour before. For now I think my workaround should do it.

Big thanks anyway, I'm very happy that we can now automate our wildcard certs with INWX :)

**Comment by ciphax** [comment]
You're welcome. I'm gonna close your pull request #3 since it is just a workaround. If the error should occur again I'll re-open this issue.

**Comment by fenhl** [comment]
I have this issue as well, please reopen.

**Comment by ciphax** [comment]
Ok, I have reopened the issue. Sadly I'm unable to reproduce it:

```
sudo letsencrypt-inwx create -d test.<my-domain> -v foobarfoo -c /etc/letsencrypt-inwx-cred && dig TXT test.<my-domain>
Record has been created successfully.

; <<>> DiG 9.10.3-P4-Ubuntu <<>> TXT test.<my-domain>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45511
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test.<my-domain>.          IN      TXT

;; ANSWER SECTION:
test.<my-domain>.   300     IN      TXT     "foobarfoo"
```

Although it is not a real solution can you try if adding a `sleep 5` in the certbot-inwx-auth script after the call to letsencrypt-inwx like @klausi did allows you to issue certificates?

**Comment by fenhl** [comment]
Yes, that seems to fix it.

**Comment by ciphax** [comment]
Okay thanks for the help. I'm gonna add a dns check to the cli which will cause it to wait until the change is visible. It would be nice if someone could test it again then since I'm unable to reproduce the problem on my server.

**Comment by ciphax** [comment]
The cli now waits until the change is publicly visible which should fix this issue. Please let me know if the issue persists.
You can get an updated .deb package from [here](https://github.com/kegato/letsencrypt-inwx/releases/tag/1.0.1).

**Comment by klausi** [comment]
The issue still exists and I had to use my "wait 2 minutes" hack from above again to renew certificates.

**Comment by ciphax** [comment]
> The issue still exists and I had to use my "wait 2 minutes" hack from above again to renew certificates.

Sorry for the delay. Are you sure that you are using the latest version? You can check the version with
```sh
$ letsencrypt-inwx --version
letsencrypt-inwx 1.1.0
```

**Comment by klausi** [comment]
Yep, happened on letsencrypt-inwx 1.1.0.

**Comment by ciphax** [comment]
> Yep, happened on letsencrypt-inwx 1.1.0.

Okay thats really strange since `letsencrypt-inwx` already uses the google dns server to verify that the created record is publicly visible. I guess our only option is to add a delay of a few seconds then. I'm going to add this delay in the next version and it would be nice if you could verify if it solves the issue.

**Comment by ciphax** [comment]
[1.1.1](https://github.com/kegato/letsencrypt-inwx/releases/tag/1.1.1) now waits 5 seconds by default. I hope this solves your issue.
