### ISSUE TITLE
Offer prebuilt binaries and link against musl libc

### ISSUE THREAD

**Issue by vbrandl** [kegato/letsencrypt-inwx#7]
While it is cool, that you offer a Debian installer package, I think the first step should be offering prebuilt binaries that everyone can download and use.
Also you should link your binaries against the musl libc to produce static binaries. Linking against glibc will result in a dynamically linked binary:
```
$ ldd usr/bin/letsencrypt-inwx 
        linux-vdso.so.1 (0x00007fff60773000)
        libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007f02cdae8000)
        libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007f02cd668000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f02cd460000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f02cd258000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f02cd038000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f02cce20000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f02cca60000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f02ce3f8000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f02cc6c8000)
```

In my experience, [ekidd/rust-musl-builder (docker)](https://hub.docker.com/r/ekidd/rust-musl-builder/) and [japaric/trust](https://github.com/japaric/trust) are good starting points.

**Comment by ciphax** [comment]
I already thought about offering a statically linked binary to fix issues like #1 and #4. travis now deploys a statically linked binary and .deb package to every release thanks to rust-musl-builder (for example [1.0.3](https://github.com/kegato/letsencrypt-inwx/releases/tag/1.0.3)).
