### ISSUE TITLE
Please do not hardcode place of config file, read config-dir or allow override

### ISSUE THREAD

**Issue by wowcut** [kegato/letsencrypt-inwx#8]
It is possibe to use certbot as non-root user with a configuration set in 
`$HOME/.config/letsencrypt/cli.ini`
where `config-dir` and `work-dir` and `logs-dir` can be set. 

If this tool would read the credentials from a file inside $HOME, it can be readable only by user and certbot can be run without root privileges  -what is good for multi-user systems like e.g. linux :)

Thanks for your attention.

**Comment by ciphax** [comment]
Actually the credential file path is not hardcoded in the program itself. But it is set as `-c` parameter in both shell scripts which are part of the .deb package. To improve non-root certbot usage those scripts now first try to use `~/.config/letsencrypt-inwx-cred` as inwx credentials. I hope this solves your problem.
