### ISSUE TITLE
Feature: follow CNAME records or allow to define CNAME of _acme-challenge.example.com

### ISSUE THREAD

**Issue by wowcut** [kegato/letsencrypt-inwx#9]
The ACME validation system [follows](https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation) [CNAME](https://en.wikipedia.org/wiki/CNAME_record) records - this allows to find a solution for problematic situations, e.g. when servers are not reachable from the public internet. You can define a CNAME for the `_acme-challenge` subdomain that points to a different domain and set the TXT record of that target domain instead of the original domain. This is also very helpful when you do not want to or can not access the nameserver of the original domain via an API. 

Of course the ACME client has to understand that concept - so there needs to be a way to define that existing CNAME or the client has to be smart enough to follow that CNAME. Probably the easy quick fix would be to add some configuration option / parameter that allows to define the actual CNAME target domain to be updated instead of always using the domain defined by the `-d` parameter.

The acme.sh client has this feature implemented as [DNS alias mode](https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode) - that wiki entry explains the concept very well. 

It would be very useful if you would like to support that feature so users of this software can do everything that is possible with LE and certbot without limitations.

Thank you very much for your attention!

**Comment by ciphax** [comment]
I see your point and this should be not hard to implement. Unfortunately I don't have much spare time at the moment but I'll look into implementing this soon.

**Comment by wowcut** [comment]
Where are you planning to get the target (the "alias") domain from? From DNS or by a parameter? 
Thank you very much for your attention and your quick answer!

**Comment by ciphax** [comment]
I think the best solution would be to lookup the real domain by using dns which should be easy to implement since we are already using [trust-dns-resolver](https://github.com/bluejekyll/trust-dns) for verifying that the record is publicly visible.

**Comment by ciphax** [comment]
This feature is now available in [version 1.1.0](https://github.com/kegato/letsencrypt-inwx/releases/tag/1.1.0).
